# Generated by Django 6.0.1 on 2026-01-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField()),
                ('category', models.IntegerField(choices=[(1, 'Catégorie 1'), (2, 'Catégorie 2'), (3, 'Catégorie 3')], default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
